spring:
  application:
    name: Tesla
  profiles:
    active: dev
server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
saluki:
  grpc:
    registryAddress: localhost:8500
  dubbo:
    registryAddress: zookeeper://127.0.0.1:2181