spring:
  application:
    name: Tesla
  profiles:
    active: dev
  metrics:
    servo:
      enabled: false
server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
saluki:
  grpc:
    registryAddress: localhost:8500
dubbo:
  registryAddress: zookeeper://127.0.0.1:2181
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/